<?php

namespace Database\Seeders;

use App\Models\PossibleOutcome;
use Illuminate\Database\Seeder;

class PossibleOutcomesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        PossibleOutcome::truncate();

        $possibleOutcomes = [
            0 => [
                'isEven' => false,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => false,
            ],
            1 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            2 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            3 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            4 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            5 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            6 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            7 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            8 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            9 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            10 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            11 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            12 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            13 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            14 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            15 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            16 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            17 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => false,
                'isBlack' => true,
            ],
            18 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => true,
                'isHigh' => false,
                'isRed' => true,
                'isBlack' => false,
            ],
            19 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],
            20 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            21 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],
            22 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            23 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],
            24 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            25 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],
            26 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            27 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],
            28 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            29 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            30 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],
            31 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            32 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],
            33 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            34 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],
            35 => [
                'isEven' => false,
                'isOdd' => true,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => false,
                'isBlack' => true,
            ],
            36 => [
                'isEven' => true,
                'isOdd' => false,
                'isLow' => false,
                'isHigh' => true,
                'isRed' => true,
                'isBlack' => false,
            ],            
        ];

        foreach ($possibleOutcomes as $num => $data) {
            PossibleOutcome::create([
                'num' => $num,
                'isEven' => $data["isEven"],
                'isOdd' => $data["isOdd"],
                'isLow' => $data["isLow"],
                'isHigh' => $data["isHigh"],
                'isRed' => $data["isRed"],
                'isBlack' => $data["isBlack"],
            ]);
        }
    }
}
